packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/wizard-remove-props.js
packages/eslint-plugin-pf-codemods/test/rules/wizard-remove-props.js

adds wizard-remove-props rule

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/aria-props.js
packages/eslint-plugin-pf-codemods/lib/rules/label-remove-isCompact.js
packages/eslint-plugin-pf-codemods/lib/rules/remove-isPseudo-props.js
packages/eslint-plugin-pf-codemods/test/rules/label-remove-isCompact.js
packages/eslint-plugin-pf-codemods/test/rules/remove-isPseudo-props.js

Closes #15, splits label into its own rule

add remove-isPseudo-props

---

generate.js
packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/alert-new-action.js
packages/eslint-plugin-pf-codemods/lib/rules/background-image-src-enum.js
packages/eslint-plugin-pf-codemods/lib/rules/card-rename-components.js
packages/eslint-plugin-pf-codemods/lib/rules/chipgroup-remove-chipgrouptoolbaritem.js
packages/eslint-plugin-pf-codemods/lib/rules/dropdown-rename-icon.js
packages/eslint-plugin-pf-codemods/lib/rules/pagination-removed-variant.js
packages/eslint-plugin-pf-codemods/lib/rules/tab-title-text.js
packages/eslint-plugin-pf-codemods/lib/rules/title-require-heading-level.js
packages/eslint-plugin-pf-codemods/lib/rules/title-size.js
packages/eslint-plugin-pf-codemods/lib/rules/wizard-remove-props.js
packages/eslint-plugin-pf-codemods/test/rules/card-rename-components.js
packages/eslint-plugin-pf-codemods/test/rules/tab-title-text.js

addImport couldn't work with `JSXIdentifier`s and had problems with the following code (it would not fix the second `<Tab>`):
```js
import { Tab } from '@patternfly/react-core';
<Tab title="Title">Content</Tab>;
<Tab title="Title">Content</Tab>;
```
This PR adds `ensureImports` which can run independently of other fixes (no state) and will run at the same time as them.

replace addImport with ensureImports

---

generate.js
packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/select-rename-checkbox.js
packages/eslint-plugin-pf-codemods/test/rules/select-rename-checkbox.js

add select-rename-checkbox

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/refactor-breakpointmods.js
packages/eslint-plugin-pf-codemods/lib/rules/remove-unused-imports.js
packages/eslint-plugin-pf-codemods/test/rules/refactor-breakpointmods.js

Closes #70 
This PR:
- removes & replaces `breakpointMods` prop from `Flex, FlexItem, ToolbarItem,, and ToolbarToggleGroup` components;
- removes & replaces `hasNoPadding` prop from `PageSection` component;
- removes & replaces `breakpoint` prop from `ToolbarToggleGroup` component.
See #70 for full details of changes.

Add refactor-breakpointmods rule

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/test/rules/chipgroup-remove-chipbutton.js
packages/eslint-plugin-pf-codemods/test/rules/expandable-rename-expandablesection.js
packages/eslint-plugin-pf-codemods/test/rules/rename-toolbar-components.js
test/test.tsx

Closes #82 
This PR adds data-codemods attributes to renamed components that would potentially be renamed a second time, and leaves removing the previous names' imports to `no-unused-imports` rule (#90)

Add data-codemods attribute on rename

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/react-icons-remove-icon.js
packages/eslint-plugin-pf-codemods/test/rules/react-icons-remove-icon.js

Closes #18 
- Checks for & removes import of `OutlinedFontAwesomeLogoFullIcon` from `@patternfly/react-icons`
- Checks for existing `@fortawesome/free-regular-svg-icons` imports & adds `fontAwesomeLogoFull` to it if needed, otherwise adds new import statement `import { fontAwesomeLogoFull } from '@fortawesome/free-regular-svg-icons';`

added react-icons-remove-icon rules & tests

---

packages/eslint-plugin-pf-codemods/lib/rules/title-size.js
packages/eslint-plugin-pf-codemods/test/rules/title-size.js

Closes #116 
Updated title-size to check that `sizeAttribute` exists before reading property on it

fix(title-size): check for sizeAttribute to be truthy before proceeding

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/divider-remove-isVertical.js
packages/eslint-plugin-pf-codemods/test/rules/v5/divider-remove-isVertical.js
packages/pf-codemods/README.md

feat(Divider): rename isVertical to orientation

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/tooltip-remove-props.js
packages/eslint-plugin-pf-codemods/test/rules/v5/tooltip-remove-props.js
packages/pf-codemods/README.md

feat(Tooltip): remove deprecated props

---

generate-replace-prop-v5.js

Quick PR demonstrating a more niche generator specifically for prop replacement.
I'm not sure if we would want to add this or not.
If we do like this idea of more specific generators I could throw together a few more for common use cases.
Thoughts?

chore(helpers): add prop replacement specific generator

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/simpleList-remove-isCurrent.js
packages/eslint-plugin-pf-codemods/test/rules/v5/simpleList-remove-isCurrent.js
packages/pf-codemods/README.md

feat(simpleList): rename isCurrent to isActive

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/remove-sticky-props.js
packages/eslint-plugin-pf-codemods/test/rules/v5/remove-sticky-props.js
packages/pf-codemods/README.md

Closes:
- #151 
- #152 
- #153 
- #154

feat(page components): remove sticky prop

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/spinner-svg-default.js
packages/eslint-plugin-pf-codemods/test/rules/v5/spinner-svg-default.js
packages/pf-codemods/README.md
packages/pf-codemods/index.js

Closes #146
This codemod removes the redundant `isSVG` flag now that the default is true. 
I tried to get the codemod to throw a warning for all `Spinner` imports but I haven't quite figured out how to modify the severity of the message (which are all thrown as errors) so I'm holding off on that for now while I tinker with it more locally.

feat(Spinner): remove isSVG

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/tabs-remove-hasSecondaryBorderBottom.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/tabs-rename-hasBorderBottom.js
packages/eslint-plugin-pf-codemods/test/rules/v5/tabs-remove-hasSecondaryBorderBottom.js
packages/eslint-plugin-pf-codemods/test/rules/v5/tabs-rename-hasBorderBottom.js
packages/pf-codemods/README.md

feat(Tabs): rename tabs props

---

package.json
packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/warn-key-codes-removed.js
packages/eslint-plugin-pf-codemods/test/rules/v5/warn-key-codes-removed.js
packages/pf-codemods/README.md
packages/pf-codemods/index.js
test/test.tsx
yarn.lock

Closes #134 
Also address some bugs and enables us to have rules as warnings rather than just errors.

feat(KEY_CODES): warn about KEY_CODES removal

---

.gitignore
packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-resizeObserver-import.js
packages/eslint-plugin-pf-codemods/test/rules/v5/charts-resizeObserver-import.js
packages/pf-codemods/README.md

Replaced react-chart `getResizeObserver` with same function from react-core.
Related to PR https://github.com/patternfly/patternfly-react/pull/8533

Charts - replace getResizeObserver

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/pagination-optionsToggle.js
packages/eslint-plugin-pf-codemods/test/rules/v5/pagination-optionsToggle.js
packages/pf-codemods/README.md

Closes #162
Doesn't have a fixer because replacing the component would be more complex than a 1:1 replacement, and also because it's unlikely this component is being used directly. If we figure out how to set the severity level this would be a good one to update to warn instead.

feat(Pagination): add codemod for optionstoggle

---

generate.js
packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/tabs-warn-children-type-changed.js
packages/eslint-plugin-pf-codemods/test/rules/v5/tabs-warn-children-type-changed.js
packages/pf-codemods/README.md
test/test.tsx

feat(Tabs): added warning that the type of Tabs children is now limited

---

packages/pf-codemods/README.md

Follow up to breaking change PR https://github.com/patternfly/patternfly-react/issues/8532
While this is fresh in my mind, wanted to update the README to indicate that we've removed the deprecated theme variant code for v5.
Created a separate codemod issue https://github.com/patternfly/pf-codemods/issues/232

Charts - remove theme variant for v5

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/react-dropzone-warn-upgrade.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/wizard-warn-button-order.js
packages/eslint-plugin-pf-codemods/test/rules/v5/react-dropzone-warn-upgrade.js
packages/pf-codemods/README.md
test/test.tsx

feat(react-dropzone): updated to latest version

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/menuItemAction-ariaLabel-required.js
packages/eslint-plugin-pf-codemods/test/rules/v5/menuItemAction-ariaLabel-required.js
packages/pf-codemods/README.md
test/test.tsx

Closes #228 
Opted to not pass in a stock `aria-label` similar to v4's ChipGroup update for `categoryName`, as since this prop won't be visually seen it might be more advantageous for consumers to manually pass the prop in based on the component's context.

feat(MenuItemAction): made aria-label prop required

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/hasCheck-prop-rename.js
packages/eslint-plugin-pf-codemods/test/rules/v5/hasCheck-prop-rename.js
packages/eslint-plugin-pf-codemods/test/rules/v5/toggle-remove-isPrimary.js
packages/pf-codemods/README.md
test/test.tsx

Closes #194 
Omitted TreeViewListItem and TreeViewRoot since they aren't exported currently.

chore(hasCheck): Updated prop name to hasCheckbox

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/table-warn-actionsColumn.js
packages/eslint-plugin-pf-codemods/test/rules/v5/table-warn-actionsColumn.js
packages/pf-codemods/README.md

chore(Table): warn ActionsColumn uses Dropdown-next

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-resizeObserver-import.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-tooltip-warning.js
packages/eslint-plugin-pf-codemods/test/rules/v5/charts-tooltip-warning.js
packages/pf-codemods/README.md
test/test.tsx

Closes #234 
Also updated some logic for the getResizeObserver file so that if there are two separate import statements from react-charts, only getResizeObserver will be updated to react-core (before it would update all imports from react-charts if getResizeObserver was found).

fix(Charts): fixed broken tooltip examples

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/alert-remove-titleHeadingLevel.js
packages/eslint-plugin-pf-codemods/test/rules/v5/alert-remove-titleHeadingLevel.js
packages/pf-codemods/README.md
test/test.tsx

chore(Alert) replace titleHeadingLevel prop

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/banner-update-variant.js
packages/eslint-plugin-pf-codemods/test/rules/v5/banner-update-variant.js
packages/pf-codemods/README.md
test/test.tsx

Closes #331 
Because of how much variety there may be when it comes to passing some variable/function reference to the `variant` prop, I opted to only include a fix for when a string is passed in. Otherwise an error message will be output if the `variant` prop is used at all (even if "default" is being passed for some reason, it lets consumers know the other variant types have changed)

feat(Banner): updated variant types

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/menu-search-rename.js
packages/eslint-plugin-pf-codemods/test/rules/v5/menu-search-rename.js
packages/pf-codemods/README.md

To `MenuSearchInput` and add `MenuSearch` as a wrapper.
Codemod for https://github.com/patternfly/patternfly-react/issues/8187

chore(Menu): rename MenuInput

---

packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/applicationLauncher-deprecated.js
packages/eslint-plugin-pf-codemods/test/rules/v5/applicationLauncher-deprecated.js
packages/pf-codemods/README.md

closes #325 
no need to create alias as we aren't offering a replacement applauncher... and it makes things much less likely to cause issues

feat(ApplicationLauncher): update to deprecated path

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/banner-update-variant.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js
packages/eslint-plugin-pf-codemods/test/rules/v5/cardHeader-update-api.js
packages/pf-codemods/README.md
test/test.tsx

Closes #274 
Feel like the error message(s) could be improved a bit... Was considering explaining how to pass stuff for CardHeaderMain and CardActions, but that might be a bit too verbose:
'CardHeaderMain and CardActions are now rendered internally within CardHeader. CardHeaderMain content should be passed directly as children to CardHeader. CardActions props and content should be passed as a CardHeaderActionsObject to CardHeader's "actions" prop.'

feat(Card): updated CardHeader API

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/table-warn-actionsColumn.js
packages/eslint-plugin-pf-codemods/test/rules/v5/table-warn-actionsColumn.js
packages/pf-codemods/README.md

Now will issue a warning, and only if both the Table import and ActionsColumn/DropdownToggle are also imported.

chore(Table): refine ActionsColumn warning

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/formgroup-remove-helpertextProps.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/formhelpertext-remove-props.js
packages/eslint-plugin-pf-codemods/test/rules/v5/formgroup-remove-helpertextProps.js
packages/eslint-plugin-pf-codemods/test/rules/v5/formhelpertext-remove-props.js
packages/pf-codemods/README.md

Removes props and warns about using `HelperText`, `HelperTextItem`, and `FormHelperText`. Had initially tried to insert the replacement node but there are many different translations that could be required based on which properties are present and what the value of the properties are (especially how the `validated` prop would translate into the new structure). I can fiddle with it more if we want to try to build the replacement HelperText block.

chore(FormGroup, FormHelperText): remove props

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/table-warn-actionsColumn.js
packages/eslint-plugin-pf-codemods/test/rules/v5/table-warn-actionsColumn.js

These warnings were popping up for *every* import if the scenario existed.. example in koku:

fixing table-warn-actionsColumn to only warn on pf table imports

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/expandableSection-onToggle-event-added.js
packages/eslint-plugin-pf-codemods/test/rules/v5/expandableSection-onToggle-event-added.js
packages/pf-codemods/README.md
test/test.tsx

feat(expandableSection): Add event to onToggle

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/no-unused-imports-v5.js
packages/eslint-plugin-pf-codemods/test/rules/v5/no-unused-imports-v5.js
packages/pf-codemods/README.md

Closes #397
Did some refactoring from the v4 rule:
- removing imports does not keep trailing commas, which were causing the file to by syntactically incorrect
- tokens are filtered with `JSXIdentifier` and `Identifier` types, so there are no misleadings, e.g. in this case: `<Title>Button</Title>` if there was an unused `Button` import, it was not removed in the previous version
- errors and fixes are more compact, 1 error and 1 group of fixes per package
- if there are no used imports from the package left, the whole import declaration is removed
The thing I was not been able to repair is to use warnings, instead of errors. There is a clash with the beta rules, which are not updated to use warnings / errors.

feat: No unused imports rule

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/multipleFileUpload-add-event-param-to-callback.js
packages/eslint-plugin-pf-codemods/test/rules/v5/multipleFileUpload-add-event-param-to-callback.js
packages/pf-codemods/README.md
test/test.tsx

feat(MultipleFileUpload): add event param to onFileDrop callback

---

packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/test/testHelpers.js
test/test.tsx

Closes #406 
@wise-king-sullyman I didn't implement logic to update re-exported components yet since I feel like that might be something that affects other codemods if we want to implement it. E.g. if we update exports here should we also update exports where a removed component is being exported, etc.

fix(moveSpecifier helper): updated logic to account for Context

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/emptyState-rename-components.js
packages/eslint-plugin-pf-codemods/test/rules/v5/emptyState-rename-components.js

Closes #369 
Simply removes some logic from the codemod to prevent the need for tests having to make multiple passes. The codemod itself won't remove unused imports, but since we have the new rule that runs on cleanup that should take care of things.

fix(EmptyState): updated codemod for renaming actions

---

packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/nav-update-callbackParams.js
packages/eslint-plugin-pf-codemods/test/rules/v5/nav-update-callbackParams.js
packages/eslint-plugin-pf-codemods/test/testHelpers.js
packages/pf-codemods/README.md
test/test.tsx

Closes #430 
Decided to update some helpers so that a custom message can be passed. I then just passed a custom message to mention that the params have been updated, and that the event property was removed from the `_edItem` object param.

fix(Nav): added event param as first param

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/card-deprecate-props.js
packages/eslint-plugin-pf-codemods/test/rules/v5/card-deprecate-props.js
packages/pf-codemods/README.md
test/test.tsx

Closes #476 
Adding the tabIndex to a Card may work better as a separate rule, but figured I'd add it into the fix that updates isSelectableRaised to isSelectable.

chore(Card): deprecated props

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-remove-props.js
packages/eslint-plugin-pf-codemods/test/rules/v5/popover-remove-props.js

closes #495 
removes fixers as a developer will have to remove instances of parameter usage as well as the parameter variable itself
fixes issue where using a function variable wasn't working, like
```
const myFunc = (fn) => {};
<Popover onHide={myFunc} />
```

fix(Popover): fix issue with identifier handlers, remove fixers

---

packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/pagination-rename-props.js
packages/eslint-plugin-pf-codemods/test/rules/v5/pagination-rename-props.js

Closes https://github.com/patternfly/pf-codemods/issues/508
Should cover most cases, where `titles` value is not a direct object expression.
This will be fixed correctly:
```
import * as React from "react";
import { Pagination } from "@patternfly/react-core";
let titlesObject = {
currPage: "test",
paginationTitle: "test",
toFirstPage: "test",
toLastPage: "test",
toNextPage: "test",
toPreviousPage: "test",
optionsToggle: "test",
};
titlesObject.paginationTitle = "test";
titlesObject["paginationTitle"] = "test";
titlesObject = {
currPage: "test",
paginationTitle: "test",
toFirstPage: "test",
toLastPage: "test",
toNextPage: "test",
toPreviousPage: "test",
optionsToggle: "test",
};
<Pagination titles={titlesObject} />;
<Pagination
titles={{
currPage: "test",
paginationTitle: "test", …
```

fix(Pagination): handle case when titles value is not a direct object expression

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/dataList-onSelectableRowChange-updated-callback.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/datalist-remove-selectableRow.js
packages/eslint-plugin-pf-codemods/test/rules/v5/dataList-onSelectableRowChange-updated-callback.js
packages/eslint-plugin-pf-codemods/test/rules/v5/datalist-remove-selectableRow.js
packages/pf-codemods/README.md
test/test.tsx

Closes #368
One thing I don't like about this fixer is that when having an object inside the `selectableRow` prop like this:
```
const selectableRowObject = { onChange: (id, event) => {}};
<DataList selectableRow={selectableRowObject} />
```
It does not change the `selectableRowObject` variable name, but changes its type from an object to a function like this:
```
const selectableRowObject = (event, id) => {};
<DataList onSelectableRowChange={selectableRowObject} />
```
I mean, it could be renamed but at the same time we should not rename consumers variables. After writing the fixer, I get why this is one of the codemods which is better to be repaired manually.

feat(Datalist): provide fixer for selectableRow prop

---

packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-remove-props.js
packages/eslint-plugin-pf-codemods/test/testHelpers.js

Closes #520
fixes callbacks like `onToggle={this.handleToggle}` to `onToggle={(event, value) => this.handleToggle(value, event)}`

fix(helpers): addCallbackParam fix for MemberExpression nodes

---

packages/pf-codemods/README.md

fix - duplicated "before" in "after" example

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/tableActionsColumn-removed-tooltipProp.js
packages/eslint-plugin-pf-codemods/test/rules/v5/tableActionsColumn-removed-tooltipProp.js
packages/pf-codemods/README.md

chore(ActionsColumn): removed tooltip prop

---

packages/eslint-plugin-pf-codemods/index.js
packages/eslint-plugin-pf-codemods/lib/helpers.js
packages/eslint-plugin-pf-codemods/lib/rules/v5/chip-update-badgeAPI.js
packages/eslint-plugin-pf-codemods/test/rules/v5/chip-update-badgeAPI.js
packages/pf-codemods/README.md

Closes #536 
Raises a warning instead of an error since leaving things as-is shouldn't break with the Core fix also merged.
I also replaced the findParentClass helper function with a more flexible helper.

feat(Chip): added badge prop

---

packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-remove-ChartThemeVariant.js
test/test.tsx

checked around and this was the only place i could find it checking specifier import.name on items that aren't from a pf repo.
closes #538

fix issue with imports that dont have import name

---

packages/eslint-plugin-pf-codemods/index.js
test/test.tsx

Fix rule name typo in warningRules array.

fix(datetimepicker): set rule intended to be a warning as a warning

---

packages/eslint-plugin-pf-codemods/src/rules/v6/labelRemoveIsOverflowLabel/label-remove-isOverflowLabel.md
packages/eslint-plugin-pf-codemods/src/rules/v6/labelRemoveIsOverflowLabel/label-remove-isOverflowLabel.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/labelRemoveIsOverflowLabel/label-remove-isOverflowLabel.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/labelRemoveIsOverflowLabel/labelRemoveIsOverflowLabelInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/labelRemoveIsOverflowLabel/labelRemoveIsOverflowLabelOutput.tsx

feat(Label): replace isOverflowLabel with variant="overflow"

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionContentRemoveIsHiddenProp/accordionContent-remove-isHidden-prop.md
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionContentRemoveIsHiddenProp/accordionContent-remove-isHidden-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionContentRemoveIsHiddenProp/accordionContent-remove-isHidden-prop.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionContentRemoveIsHiddenProp/accordionContentRemoveIsHiddenPropInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionContentRemoveIsHiddenProp/accordionContentRemoveIsHiddenPropOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItem-warn-update-markup.md
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItem-warn-update-markup.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItem-warn-update-markup.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItemWarnUpdateMarkupInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItemWarnUpdateMarkupOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggle-move-isExpanded-prop.md
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggle-move-isExpanded-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggle-move-isExpanded-prop.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggleMoveIsExpandedPropInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggleMoveIsExpandedPropOutput.tsx

feat(Accordion): updates props

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadRemoveHasNoPaddingProp/drawerHead-remove-hasNoPadding-prop.md
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadRemoveHasNoPaddingProp/drawerHead-remove-hasNoPadding-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadRemoveHasNoPaddingProp/drawerHead-remove-hasNoPadding-prop.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadRemoveHasNoPaddingProp/drawerHeadRemoveHasNoPaddingPropInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadRemoveHasNoPaddingProp/drawerHeadRemoveHasNoPaddingPropOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadWarnUpdatedMarkup/drawerHead-warn-updated-markup.md
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadWarnUpdatedMarkup/drawerHead-warn-updated-markup.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadWarnUpdatedMarkup/drawerHead-warn-updated-markup.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadWarnUpdatedMarkup/drawerHeadWarnUpdatedMarkupInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadWarnUpdatedMarkup/drawerHeadWarnUpdatedMarkupOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerReplaceColorVariantLight200/drawer-replace-colorVariant-light200.md
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerReplaceColorVariantLight200/drawer-replace-colorVariant-light200.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerReplaceColorVariantLight200/drawer-replace-colorVariant-light200.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerReplaceColorVariantLight200/drawerReplaceColorVariantLight200Input.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerReplaceColorVariantLight200/drawerReplaceColorVariantLight200Output.tsx

feat(Drawer): removed and updated props

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsRenamedIsSecondaryProp/tabs-renamed-isSecondary-prop.md
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsRenamedIsSecondaryProp/tabs-renamed-isSecondary-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsRenamedIsSecondaryProp/tabs-renamed-isSecondary-prop.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsRenamedIsSecondaryProp/tabsRenamedIsSecondaryPropInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsRenamedIsSecondaryProp/tabsRenamedIsSecondaryPropOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsReplaceVariantLight300/tabs-replace-variant-light300.md
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsReplaceVariantLight300/tabs-replace-variant-light300.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsReplaceVariantLight300/tabs-replace-variant-light300.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsReplaceVariantLight300/tabsReplaceVariantLight300Input.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsReplaceVariantLight300/tabsReplaceVariantLight300Output.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsUpdateMarkup/tabs-update-markup.md
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsUpdateMarkup/tabs-update-markup.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsUpdateMarkup/tabs-update-markup.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsUpdateMarkup/tabsUpdateMarkupInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/tabsUpdateMarkup/tabsUpdateMarkupOutput.tsx

feat(Tabs): updated props and markup

---

packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveTertiaryVariant/nav-remove-tertiary-variant.md
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveTertiaryVariant/nav-remove-tertiary-variant.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveTertiaryVariant/nav-remove-tertiary-variant.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveTertiaryVariant/navRemoveTertiaryVariantInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveTertiaryVariant/navRemoveTertiaryVariantOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveThemeProp/nav-remove-theme-prop.md
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveThemeProp/nav-remove-theme-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveThemeProp/nav-remove-theme-prop.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveThemeProp/navRemoveThemePropInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveThemeProp/navRemoveThemePropOutput.tsx

feat(Nav): props updates

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleWarnIconOnlyToggle/menuToggle-warn-iconOnly-toggle.md
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleWarnIconOnlyToggle/menuToggle-warn-iconOnly-toggle.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleWarnIconOnlyToggle/menuToggle-warn-iconOnly-toggle.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleWarnIconOnlyToggle/menuToggleWarnIconOnlyToggleInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleWarnIconOnlyToggle/menuToggleWarnIconOnlyToggleOutput.tsx

feat(MenuToggle): updated recommended icon usage

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuItemActionWarnUpdateMarkup/menuItemAction-warn-update-markup.md
packages/eslint-plugin-pf-codemods/src/rules/v6/menuItemActionWarnUpdateMarkup/menuItemAction-warn-update-markup.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuItemActionWarnUpdateMarkup/menuItemAction-warn-update-markup.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuItemActionWarnUpdateMarkup/menuItemActionWarnUpdateMarkupInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/menuItemActionWarnUpdateMarkup/menuItemActionWarnUpdateMarkupOutput.tsx

feat(Menu): updated markup for MenuItemAction

---

packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.md
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeaderMoveIntoEmptyStateInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeaderMoveIntoEmptyStateOutput.tsx

feat(EmptyState): Add rule to move EmptyStateHeader into EmptyState

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/checkboxRadioReplaceIsLabelBeforeButton/checkbox-radio-replace-isLabelBeforeButton.md
packages/eslint-plugin-pf-codemods/src/rules/v6/checkboxRadioReplaceIsLabelBeforeButton/checkbox-radio-replace-isLabelBeforeButton.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/checkboxRadioReplaceIsLabelBeforeButton/checkbox-radio-replace-isLabelBeforeButton.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/checkboxRadioReplaceIsLabelBeforeButton/checkboxRadioReplaceIsLabelBeforeButtonInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/checkboxRadioReplaceIsLabelBeforeButton/checkboxRadioReplaceIsLabelBeforeButtonOutput.tsx

Closes #583 
Wait until the underlying react PR https://github.com/patternfly/patternfly-react/pull/10016 is approved and merged before merging this codemod PR.

feat(Checkbox/Radio): replace isLabelBeforeButton with labelPosition="start"

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formGroupRenameLabelIcon/formGroup-rename-labelIcon.md
packages/eslint-plugin-pf-codemods/src/rules/v6/formGroupRenameLabelIcon/formGroup-rename-labelIcon.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formGroupRenameLabelIcon/formGroup-rename-labelIcon.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formGroupRenameLabelIcon/formGroupRenameLabelIconInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/formGroupRenameLabelIcon/formGroupRenameLabelIconOutput.tsx

Closes #563
Wait until the underlying react PR https://github.com/patternfly/patternfly-react/pull/10016 is approved and merged before merging this codemod PR.
Possible improvements / thoughts:
- trying to adjust whatever consumer is passing to `labelIcon` to use the new FormGroupLabelHelp component is nearly impossible and there would be lots of edge cases, so I would rather not do that
- can we add a comment directly to the code, which would recommend using `FormGroupLabelHelp` component for the `labelHelp` prop? Something like: 
input:
```
<FormGroup labelIcon={<button>Help icon</button>} />
```
output:
```
<FormGroup labelHelp={/* CODEMODS RECOMMENDATION: use FormGroupLabelHelp component */ <button>Help icon</button>} />
```
or is a message in the codemod error sufficient?

feat(FormGroup): rename labelIcon to labelHelp

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipDeprecated/chip-deprecated.md
packages/eslint-plugin-pf-codemods/src/rules/v6/chipDeprecated/chip-deprecated.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipDeprecated/chip-deprecated.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipDeprecated/chipDeprecatedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/chipDeprecated/chipDeprecatedOutput.tsx

feat(Chip) update to deprecated path

---

packages/class-name-updater/CHANGELOG.md
packages/class-name-updater/package.json
packages/pf-codemods/CHANGELOG.md
packages/pf-codemods/package.json
yarn.lock

Upgrades TypeScript to the latest available version. This helps projects that are trying to apply the codemod on modern TypeScript code bases, as those will currently error out on unsupported syntax.

chore(deps): upgrade TypeScript to latest version

---

generators/src/write-rule.ts

chore(genericRule generator): use actual types from estree-jsx and eslint

---

packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.md
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObjectRenamedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObjectRenamedOutput.tsx

feat(FormFiledGroupHeaderTitleTextObject): interface renamed (typo)

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/getFromPackage.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/pfPackageMatches.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.ts

Uses helpers from #602 which should be merged first before this PR.
Closes #595

feat(EmptyState): support icons passed directly to EmptyStateHeader

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/treeViewWarnSelectableStylingModifierRemoved/treeView-warn-selectable-styling-modifier-removed.md
packages/eslint-plugin-pf-codemods/src/rules/v6/treeViewWarnSelectableStylingModifierRemoved/treeView-warn-selectable-styling-modifier-removed.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/treeViewWarnSelectableStylingModifierRemoved/treeView-warn-selectable-styling-modifier-removed.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/treeViewWarnSelectableStylingModifierRemoved/treeViewWarnSelectableStylingModifierRemovedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/treeViewWarnSelectableStylingModifierRemoved/treeViewWarnSelectableStylingModifierRemovedOutput.tsx

feat(TreeView): warning for removal of selectable styling modifier

---

packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObjectRenamedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObjectRenamedOutput.tsx

feat(FormFiledGroupHeaderTitleTextObject): handle export specifier

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/getImportDeclaration.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.md
packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chipReplaceWithLabelInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chipReplaceWithLabelOutput.tsx

feat(Chip) replace with Label

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/JSXAttributes.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/helpers.js
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerContentReplaceNoBackgroundColorVariant/drawerContent-replace-noBackground-colorVariant.md
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerContentReplaceNoBackgroundColorVariant/drawerContent-replace-noBackground-colorVariant.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerContentReplaceNoBackgroundColorVariant/drawerContent-replace-noBackground-colorVariant.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerContentReplaceNoBackgroundColorVariant/drawerContentReplaceNoBackgroundColorVariantInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/drawerContentReplaceNoBackgroundColorVariant/drawerContentReplaceNoBackgroundColorVariantOutput.tsx

Closes #624 
Also types findVariableDeclaration helper and adds some other helpers.

feat(DrawerContent): removed no-background colorVariant

---

packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyState-nonExported-components.md
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyState-nonExported-components.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyState-nonExported-components.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyStateNonExportedComponentsInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyStateNonExportedComponentsOutput.tsx

fix(EmptyState): components no longer exported

---

packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.ts

fix(Chip): Remove isReadOnly prop during label conversion

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/testHelpers.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modal-deprecated.md
packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modal-deprecated.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modal-deprecated.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modalDeprecatedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modalDeprecatedOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/modalNextPromoted/modalNext-promoted.md
packages/eslint-plugin-pf-codemods/src/rules/v6/modalNextPromoted/modalNext-promoted.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/modalNextPromoted/modalNext-promoted.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/modalNextPromoted/modalNextPromotedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/modalNextPromoted/modalNextPromotedOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarReplacedSpacerSpaceItems/toolbar-replaced-spacer-spaceItems.test.ts

Closes #636 
Also creates some helpers for tests, mainly for when a single rule is expected to update/throw for several components.

feat(Modal): promoted Next implementation

---

packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSection-update-variant-values.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSection-update-variant-values.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSectionUpdateVariantValuesInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSectionUpdateVariantValuesOutput.tsx

fix(PageSection): updated logic to account for variant enum

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/getEndRange.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/noUnusedImportsV6/no-unused-imports-v6.md
packages/eslint-plugin-pf-codemods/src/rules/v6/noUnusedImportsV6/no-unused-imports-v6.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/noUnusedImportsV6/no-unused-imports-v6.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/noUnusedImportsV6/noUnusedImportsV6Input.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/noUnusedImportsV6/noUnusedImportsV6Output.tsx
tsconfig.base.json

fix(noUnusedImports): Add unused import removal for v6 rules

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/JSXAttributes.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageBreadcrumbAndSectionWarnUpdatedWrapperLogic/pageBreadcrumbAndSection-warn-updated-wrapperLogic.md
packages/eslint-plugin-pf-codemods/src/rules/v6/pageBreadcrumbAndSectionWarnUpdatedWrapperLogic/pageBreadcrumbAndSection-warn-updated-wrapperLogic.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageBreadcrumbAndSectionWarnUpdatedWrapperLogic/pageBreadcrumbAndSection-warn-updated-wrapperLogic.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageBreadcrumbAndSectionWarnUpdatedWrapperLogic/pageBreadcrumbAndSectionWarnUpdatedWrapperLogicInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageBreadcrumbAndSectionWarnUpdatedWrapperLogic/pageBreadcrumbAndSectionWarnUpdatedWrapperLogicOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageNavigationRemoveComponent/pageNavigation-remove-component.md
packages/eslint-plugin-pf-codemods/src/rules/v6/pageNavigationRemoveComponent/pageNavigation-remove-component.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageNavigationRemoveComponent/pageNavigation-remove-component.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageNavigationRemoveComponent/pageNavigationRemoveComponentInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageNavigationRemoveComponent/pageNavigationRemoveComponentOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionRemoveNavType/pageSection-remove-nav-type.md
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionRemoveNavType/pageSection-remove-nav-type.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionRemoveNavType/pageSection-remove-nav-type.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionRemoveNavType/pageSectionRemoveNavTypeInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionRemoveNavType/pageSectionRemoveNavTypeOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageWarnUpdatedMarkup/page-warn-updated-markup.md
packages/eslint-plugin-pf-codemods/src/rules/v6/pageWarnUpdatedMarkup/page-warn-updated-markup.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageWarnUpdatedMarkup/page-warn-updated-markup.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/pageWarnUpdatedMarkup/pageWarnUpdatedMarkupInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/pageWarnUpdatedMarkup/pageWarnUpdatedMarkupOutput.tsx

feat(Page): updated logic to allow section grouping

---

packages/eslint-plugin-pf-codemods/src/rules/v6/wizardStepUpdatedBodyTyping/wizardStep-updated-body-typing.md
packages/eslint-plugin-pf-codemods/src/rules/v6/wizardStepUpdatedBodyTyping/wizardStep-updated-body-typing.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/wizardStepUpdatedBodyTyping/wizardStep-updated-body-typing.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/wizardStepUpdatedBodyTyping/wizardStepUpdatedBodyTypingInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/wizardStepUpdatedBodyTyping/wizardStepUpdatedBodyTypingOutput.tsx

fix(WizardStep): prevented omitting the WizardBody component

---

packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.md
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentOutput.tsx

Closes #663 
This is a failing codemod.
It will not work in case of nested elements (because we modify the outer wrapper, it cannot detect the children, because the range has been changed). I remember I did a workaround to this issue in the chipToLabel codemod, something with the `getAllJSXElements` helper.

feat: Text to Content

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/noDuplicateImportSpecifiers/no-duplicate-import-specifiers.md
packages/eslint-plugin-pf-codemods/src/rules/v6/noDuplicateImportSpecifiers/no-duplicate-import-specifiers.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/noDuplicateImportSpecifiers/no-duplicate-import-specifiers.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/noDuplicateImportSpecifiers/noDuplicateImportSpecifiersInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/noDuplicateImportSpecifiers/noDuplicateImportSpecifiersOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentOutput.tsx

feat: No duplicate import specifiers rule

---

generators/src/helpers.js
generators/src/helpers.ts
generators/src/plop-interfaces.ts
generators/src/write-readme.ts
generators/src/write-rule.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/nodeMatches.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItem-warn-update-markup.ts
plopFile.cjs

chore(generators): made enhancements to generator files

---

packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentOutput.tsx

fix(textReplaceWithContent): fix nested JSXElements handling

---

packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentBodyTextPropsUpdate/component-groups-unavailableContent-bodyText-props-update.md
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentBodyTextPropsUpdate/component-groups-unavailableContent-bodyText-props-update.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentBodyTextPropsUpdate/component-groups-unavailableContent-bodyText-props-update.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentBodyTextPropsUpdate/componentGroupsUnavailableContentBodyTextPropsUpdateInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentBodyTextPropsUpdate/componentGroupsUnavailableContentBodyTextPropsUpdateOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/component-groups-unavailable-content-rename-props.md
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/component-groups-unavailable-content-rename-props.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/component-groups-unavailable-content-rename-props.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/componentGroupsUnavailableContentRenamePropsInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/componentGroupsUnavailableContentRenamePropsOutput.tsx

Closes #732 
- because `unavailableBodyPreStatusLinkText` and `unavailableBodyPostStatusLinkText` has already been renamed to `preLinkBodyText` and `postLinkBodyText` and are being renamed again and merged to only one `bodyText` prop, I also modified the `component-groups-unavailable-content-rename-props` rule to only rename `unavailableTitleText`
- `statusPageLinkText` prop is now being used for a **primary** button instead of a link button -> the text should be capitalized (as it is being done with the default "status page" -> "Status page")

feat(UnavailableContent): update props to use bodyText

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts

Looks like we typo'd a warning rule

fix(Pagination): Fix rule to report as a warning instead of an error

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/nodeIsComponentNamed.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/loginMainFooterLinksItemStructureUpdated/loginMainFooterLinksItem-structure-updated.ts

refactor: get rid of nodeIsComponentNamed helper

---

packages/eslint-plugin-pf-codemods/src/ruleCuration.ts
packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/dataCodemodsCleanup/data-codemods-cleanup.md
packages/eslint-plugin-pf-codemods/src/rules/v6/dataCodemodsCleanup/data-codemods-cleanup.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/dataCodemodsCleanup/data-codemods-cleanup.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/dataCodemodsCleanup/dataCodemodsCleanupInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/dataCodemodsCleanup/dataCodemodsCleanupOutput.tsx
packages/pf-codemods/README.md
packages/pf-codemods/index.js
packages/pf-codemods/scripts/baseReadMe.md

Closes #723 
Also updates `baseReadme.md` file.

feat: data-codemods cleanup rule

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/JSXAttributes.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/childrenIsEmpty.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/getChildJSXElementByName.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/makeJSXElementSelfClosing.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/button-moveIcons-icon-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/button-moveIcons-icon-prop.ts

Closes #694 
Also supports Icon / react-icons being used in children attribute.

feat(buttonMoveIconsIconProp rule): transform to self closing tag

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/renameComponent.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsContentHeaderRenameToPageHeader/component-groups-contentHeader-rename-to-pageHeader.md
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsContentHeaderRenameToPageHeader/component-groups-contentHeader-rename-to-pageHeader.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsContentHeaderRenameToPageHeader/component-groups-contentHeader-rename-to-pageHeader.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsContentHeaderRenameToPageHeader/componentGroupsContentHeaderRenameToPageHeaderInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsContentHeaderRenameToPageHeader/componentGroupsContentHeaderRenameToPageHeaderOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/component-groups-invalidObject-rename-props.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/component-groups-invalidObject-rename-props.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameToMissingPage/component-groups-invalidObject-rename-to-missingPage.md
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameToMissingPage/component-groups-invalidObject-rename-to-missingPage.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameToMissingPage/component-groups-invalidObject-rename-to-missingPage.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameToMissingPage/componentGroupsInvalidObjectRenameToMissingPageInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameToMissingPage/componentGroupsInvalidObjectRenameToMissingPageOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameProps/component-groups-notAuthorized-rename-props.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameProps/component-groups-notAuthorized-rename-props.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameToUnauthorizedAccess/component-groups-notAuthorized-rename-to-unauthorizedAccess.md
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameToUnauthorizedAccess/component-groups-notAuthorized-rename-to-unauthorizedAccess.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameToUnauthorizedAccess/component-groups-notAuthorized-rename-to-unauthorizedAccess.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameToUnauthorizedAccess/componentGroupsNotAuthorizedRenameToUnauthorizedAccessInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsNotAuthorizedRenameToUnauthorizedAccess/componentGroupsNotAuthorizedRenameToUnauthorizedAccessOutput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/dataCodemodsCleanup/data-codemods-cleanup.ts

Closes #769, #772, #773 
- Also changes the `renameComponent` helper to update node name when default import matches the component name, e.g.: `import InvalidObject from '@patternfly/react-component-groups/dist/cjs/InvalidObject/index'; <InvalidObject />` will update to `import MissingPage from '@patternfly/react-component-groups/dist/cjs/MissingPage/index'; <MissingPage data-codemods />`

feat(component groups): rename various components

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tileDeprecated/tile-deprecated.md
packages/eslint-plugin-pf-codemods/src/rules/v6/tileDeprecated/tile-deprecated.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tileDeprecated/tile-deprecated.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/tileDeprecated/tileDeprecatedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/tileDeprecated/tileDeprecatedOutput.tsx

Codemod for https://github.com/patternfly/patternfly-react/pull/10821
Closes https://github.com/patternfly/pf-codemods/issues/731.

feat(Tile): add deprecated import update mod

---

packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.md
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeaderMoveIntoEmptyStateInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeaderMoveIntoEmptyStateOutput.tsx

feat(EmptyState): make titleText optional

---

packages/class-name-updater/src/classNameUpdate.ts
packages/class-name-updater/test/test.css

fix(class-name-updater): ignore css vars when running in v6 mode

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/JSXAttributes.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleRemoveSplitButtonOptions/menuToggle-remove-splitButtonOptions.md
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleRemoveSplitButtonOptions/menuToggle-remove-splitButtonOptions.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleRemoveSplitButtonOptions/menuToggle-remove-splitButtonOptions.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleRemoveSplitButtonOptions/menuToggleRemoveSplitButtonOptionsInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/menuToggleRemoveSplitButtonOptions/menuToggleRemoveSplitButtonOptionsOutput.tsx

Closes #781 
- also some helper updates

feat(MenuToggle): remove splitButtonOptions prop and interface

---

packages/eslint-plugin-pf-codemods/src/rules/v6/chartsImportMoved/chartsImport-moved.md
packages/eslint-plugin-pf-codemods/src/rules/v6/chartsImportMoved/chartsImport-moved.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chartsImportMoved/chartsImport-moved.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/chartsImportMoved/chartsImportMovedInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/chartsImportMoved/chartsImportMovedOutput.tsx
packages/pf-codemods/README.md

This code mod updates existing import paths to our victory directory.
https://github.com/patternfly/patternfly-react/issues/11090

feat(charts): import charts from @patternfly/react-charts/victory

---

packages/class-name-updater/src/classNameUpdate.ts

Closes #802
If the path given to class name updater is an absolute path, the tool raises an error. It adds the current working dir regardless of the path type.
This patch fixes this issue and only adds the current working dir if the file path is not absolute.

fix: class name updater does not support absolute paths

---

packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts

fix(TextReplaceWithContent): update dist import path

---

packages/eslint-plugin-pf-codemods/src/rules/v6/chartsImportMoved/chartsImport-moved.md
packages/pf-codemods/README.md

Update notes to describe Victory as an optional peer dependency
https://github.com/patternfly/patternfly-react/issues/11125

Update notes for react-charts

---

packages/pf-codemods/README.md
packages/pf-codemods/index.js
packages/pf-codemods/package.json
packages/pf-codemods/scripts/baseReadMe.md
yarn.lock

Closes https://github.com/patternfly/pf-codemods/issues/756

chore: update CLI to force choosing PF version

---

packages/eslint-plugin-pf-codemods/package.json
packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/nodeMatches/checkMatchingImportSpecifier.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/renameInterface.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectPropsRenameToMissingPageProps/component-groups-invalidObjectProps-rename-to-missingPageProps.md
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectPropsRenameToMissingPageProps/component-groups-invalidObjectProps-rename-to-missingPageProps.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectPropsRenameToMissingPageProps/component-groups-invalidObjectProps-rename-to-missingPageProps.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectPropsRenameToMissingPageProps/componentGroupsInvalidObjectPropsRenameToMissingPagePropsInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectPropsRenameToMissingPageProps/componentGroupsInvalidObjectPropsRenameToMissingPagePropsOutput.tsx
yarn.lock

Closes #786 
Adds a helper to rename interface. I added the `@typescript-eslint/utils` package for that reason to type the given typescript Nodes. However it does it not fit 100% with the current `Rule.RuleContext` we are using, so I had to do the `node as unknown as Node` casting. 
In the future we might migrate to use `@typescript-eslint/utils` instead of `estree-jsx` entirely, but it would require basically updating every rule and helpers, so I don't know if it is worth it.

feat(componentGroups): rename InvalidObjectProps to MissingPageProps

---

packages/eslint-plugin-pf-codemods/src/rules/helpers/getFromPackage.ts
packages/eslint-plugin-pf-codemods/src/rules/helpers/renameInterface.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectPropsRenameToMissingPageProps/component-groups-invalidObjectProps-rename-to-missingPageProps.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/formFiledGroupHeaderTitleTextObjectRenamed/formFiledGroupHeaderTitleTextObject-renamed.ts

Closes #622
- refactors and fixes the `renameInterface` helper to support custom messages and check `ExportSpecifier` too
- modifies FormFiledGroupHeaderTitleTextObject rule to use the helper (which uses the correct TS node types, unlike the rule before)

fix(formFiledGroupHeaderTitleTextObject): use renameInterface helper

---

packages/eslint-plugin-pf-codemods/src/rules/v6/expandableSectionRemoveIsActiveProp/expandableSection-remove-isActive-prop.md
packages/eslint-plugin-pf-codemods/src/rules/v6/expandableSectionRemoveIsActiveProp/expandableSection-remove-isActive-prop.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/expandableSectionRemoveIsActiveProp/expandableSection-remove-isActive-prop.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/expandableSectionRemoveIsActiveProp/expandableSectionRemoveIsActivePropInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/expandableSectionRemoveIsActiveProp/expandableSectionRemoveIsActivePropOutput.tsx

feat(ExpandableSection): Remove isActive prop

---

.github/workflows/release.yml
.github/workflows/test.yml

fix: updated the cache to v4 due to EOL of v2.

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/enableAnimations/enable-animations.md
packages/eslint-plugin-pf-codemods/src/rules/v6/enableAnimations/enable-animations.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/enableAnimations/enable-animations.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/enableAnimations/enableAnimationsInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/enableAnimations/enableAnimationsOutput.tsx

feat/841: add optional codemod and flag for enabling animations

---

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonSupportFavoriteVariant/button-support-favorite-variant.md
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonSupportFavoriteVariant/button-support-favorite-variant.test.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonSupportFavoriteVariant/button-support-favorite-variant.ts
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonSupportFavoriteVariant/buttonSupportFavoriteVariantInput.tsx
packages/eslint-plugin-pf-codemods/src/rules/v6/buttonSupportFavoriteVariant/buttonSupportFavoriteVariantOutput.tsx
packages/pf-codemods/README.md

feat(853): favorite button codemod
