patternfly/pf-codemods

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/background-image-src-enum.js, packages/eslint-plugin-pf-codemods/test/rules/background-image-src-enum.js
=> add background-image-src-enum

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/skip-to-content-remove-component.js, packages/eslint-plugin-pf-codemods/test/rules/skip-to-content-remove-component.js
=> add skip-to-content rule

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/alert-new-action.js, packages/eslint-plugin-pf-codemods/lib/rules/skip-to-content-remove-component.js, packages/eslint-plugin-pf-codemods/test/rules/alert-new-action.js
=> add alert-new-action

generate.js, packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/chipgroup-remove-chipbutton.js, packages/eslint-plugin-pf-codemods/lib/rules/chipgroup-remove-chipgrouptoolbaritem.js, packages/eslint-plugin-pf-codemods/lib/rules/chipgroup-remove-props.js, packages/eslint-plugin-pf-codemods/test/rules/chipgroup-remove-chipbutton.js, packages/eslint-plugin-pf-codemods/test/rules/chipgroup-remove-chipgrouptoolbaritem.js, packages/eslint-plugin-pf-codemods/test/rules/chipgroup-remove-props.js, packages/pf-codemods/RULES.md
=> add chipgroup rules

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/chipgroup-remove-chipgrouptoolbaritem.js, packages/eslint-plugin-pf-codemods/lib/rules/dropdown-rename-icon.js, packages/eslint-plugin-pf-codemods/test/rules/dropdown-rename-icon.js
=> add dropdown-rename-icon

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/dropdown-toggle-rename-iconComponent.js, packages/eslint-plugin-pf-codemods/test/rules/dropdown-toggle-rename-iconComponent.js
=> add dropdown-toggle-rename-iconComponent

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/empty-state-icon-removed-props.js, packages/eslint-plugin-pf-codemods/test/rules/empty-state-icon-removed-props.js
=> add empty-state-icon-removed-props

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/pagination-removed-variant.js, packages/eslint-plugin-pf-codemods/test/rules/pagination-removed-variant.js
=> add pagination-removed-variant

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/rename-noPadding.js, packages/eslint-plugin-pf-codemods/test/rules/rename-noPadding.js
=> add rename-noPadding

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/form-fix-isValid.js, packages/eslint-plugin-pf-codemods/test/rules/form-fix-isValid.js
=> add form-fix-isValid

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/tab-rename-variant.js, packages/eslint-plugin-pf-codemods/package-lock.json, packages/eslint-plugin-pf-codemods/test/rules/tab-rename-variant.js
=> tab-rename-variant

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/remove-unused-imports.js, packages/eslint-plugin-pf-codemods/test/rules/remove-unused-imports.js
Closes: #39 
Removes unused imports and also checks for surrounding commas and alias and removes those as well if needed.
=> remove-unused-imports

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/nav-list-variant.js, packages/eslint-plugin-pf-codemods/test/rules/nav-list-variant.js
Closes #12 
Fixes for NavList variant property being moved to Nav component.
=> Nav list variant

packages/pf-codemods/index.js
Example of one rule: (remove-unused-imports)
Example of two rules: (remove-unused-imports background-image-src-enum)
No rules:
=> now able to specify rules on cli

packages/eslint-plugin-pf-codemods/lib/rules/nav-list-variant.js, packages/eslint-plugin-pf-codemods/test/rules/nav-list-variant.js
=> handle NavVariants

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/datatoolbar-rename-toolbar.js, packages/eslint-plugin-pf-codemods/test/rules/datatoolbar-rename-toolbar.js
=> Rename DataToolbar to Toolbar

packages/pf-codemods/index.js
when providing rules the rules should run correctly. This fix allows this to happen.
Single Rule:
Multiple Rule:
=> fix for specifying rule(s) on the cli

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/chartVoronoiContainer-remove-allowTooltip.js, packages/eslint-plugin-pf-codemods/test/rules/chartVoronoiContainer-remove-allowTooltip.js
=> fixer to remove allowTooltip from  chartVoronoiContainer

packages/eslint-plugin-pf-codemods/lib/rules/card-rename-components.js, packages/eslint-plugin-pf-codemods/test/rules/card-rename-components.js
=> don't rename if new imports exist

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/chipgroup-remove-props.js, packages/eslint-plugin-pf-codemods/test/rules/chipgroup-remove-props.js
=> add leaveComment

packages/pf-codemods/.eslintrc.json, packages/pf-codemods/index.js, packages/pf-codemods/package.json, yarn.lock
=> feat(cli): use commander and allow including/excluding rules

packages/pf-codemods/README.md
Update docs for release.
Closes #103
=> official release :tada:

packages/eslint-plugin-pf-codemods/lib/rules/tab-title-text.js, packages/eslint-plugin-pf-codemods/test/rules/tab-title-text.js, test/test.tsx
Closes https://github.com/patternfly/pf-codemods/issues/102
=> support member expression

packages/pf-codemods/index.js
=> remove resolvePluginsRelativeTo

packages/pf-codemods/index.js
=> add parser and parseroptions

packages/eslint-plugin-pf-codemods/package.json, packages/pf-codemods/package.json
Bump eslint to debug parser loading
=> bump eslint and typescript parser

package-lock.json
=> bump package-lock.json

generate.js, packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/tableComposable-remove-hasSelectableRowCaption.js, packages/eslint-plugin-pf-codemods/test/rules/v5/tableComposable-remove-hasSelectableRowCaption.js, packages/pf-codemods/README.md
closes https://github.com/patternfly/pf-codemods/issues/144
=> feat(TableComposable): remove hasSelectableRowCaption

.github/workflows/check-pr.yml, .github/workflows/release.yml
=> Updated branch to main for workflows

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/fileUpload-remove-onChange.js, packages/eslint-plugin-pf-codemods/test/rules/v5/fileUpload-remove-onChange.js, packages/pf-codemods/README.md
=> feat(FileUpload): remove onChange prop

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/resizeObserver-function-param.js, packages/eslint-plugin-pf-codemods/test/rules/v5/resizeObserver-function-param.js, packages/pf-codemods/README.md
=> feat(ResizeObserver): added new parameter

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/pagination-rename-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/pagination-rename-props.js, packages/pf-codemods/README.md
Closes #169
Since the other Pagination components aren't exposed I opted to not mention them in any messages.
=> feat(Pagination): renamed props

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/card-remove-isHoverable.js, packages/eslint-plugin-pf-codemods/test/rules/v5/card-remove-isHoverable.js, packages/pf-codemods/README.md
=> feat(card): remove isHoverable

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/accordion-rename-displaySize-large.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/expandable-section-rename-displaySize-large.js, packages/eslint-plugin-pf-codemods/test/rules/v5/accordion-rename-displaySize-large.js, packages/eslint-plugin-pf-codemods/test/rules/v5/expandable-section-rename-displaySize-large.js, packages/pf-codemods/README.md
=> feat(accordion, expandablesection): rename displaySize prop value

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/toggle-remove-isPrimary.js, packages/eslint-plugin-pf-codemods/test/rules/v5/toggle-remove-isPrimary.js, packages/pf-codemods/README.md
=> feat(Toggle): replace isPrimary with toggleVariant="primary"

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/remove-removeFindDomNode.js, packages/eslint-plugin-pf-codemods/test/rules/v5/remove-removeFindDomNode.js, packages/pf-codemods/README.md
=> feat(misc) - remove removeFindDomNode prop

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-remove-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/popover-remove-props.js, packages/pf-codemods/README.md
=> feat(Popover): remove deprecated props and params

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/clipboardCopy-remove-popoverPosition.js, packages/eslint-plugin-pf-codemods/test/rules/v5/clipboardCopy-remove-popoverPosition.js, packages/pf-codemods/README.md
=> feat(ClipboardCopy): removed PopoverPosition type

CONTRIBUTING.md, packages/eslint-plugin-pf-codemods/index.js
=> feat(rules): add severity customization

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/horizontalSubnav-ariaLabel.js, packages/eslint-plugin-pf-codemods/test/rules/v5/horizontalSubnav-ariaLabel.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Nav): updated aria-label default value

packages/eslint-plugin-pf-codemods/lib/rules/v5/remove-toggleMenuBaseProps.js, packages/eslint-plugin-pf-codemods/test/rules/v5/remove-toggleMenuBaseProps.js, packages/pf-codemods/README.md
=> ToggleMenuBaseProps - remove

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/wizard-warn-button-order.js, packages/eslint-plugin-pf-codemods/test/rules/v5/wizard-warn-button-order.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Wizard): updated button order

packages/eslint-plugin-pf-codemods/lib/rules/v5/accordion-rename-AccordionExpandedContentBody.js, packages/eslint-plugin-pf-codemods/test/rules/v5/accordion-rename-AccordionExpandedContentBody.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(AccordionExpandableContent): rename expanded refs

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/applicationLauncher-warn-input.js, packages/eslint-plugin-pf-codemods/test/rules/v5/applicationLauncher-warn-input.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(ApplicationLauncher): updated input to SearchInput

packages/eslint-plugin-pf-codemods/lib/rules/v5/dropdownToggle-remove-isPrimary.js, packages/eslint-plugin-pf-codemods/test/rules/v5/dropdownToggle-remove-isPrimary.js, packages/pf-codemods/README.md, test/test.tsx
=> dropdown toggle replace is primary

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/card-warn-component.js, packages/eslint-plugin-pf-codemods/test/rules/v5/card-warn-component.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(card): add warning for card default component

packages/eslint-plugin-pf-codemods/lib/rules/v5/clipboardCopy-remove-switchDelay.js, packages/eslint-plugin-pf-codemods/test/rules/v5/clipboardCopy-remove-switchDelay.js, packages/pf-codemods/README.md
=> feat(ClipboardCopy): remove switchDelay prop

packages/eslint-plugin-pf-codemods/lib/rules/v5/react-dropzone-warn-upgrade.js, packages/eslint-plugin-pf-codemods/test/rules/v5/react-dropzone-warn-upgrade.js, packages/pf-codemods/README.md
=> chore(react-dropzone): Updated rule to specify type changes

packages/eslint-plugin-pf-codemods/lib/rules/v5/alert-remove-ariaLabel.js, packages/eslint-plugin-pf-codemods/test/rules/v5/alert-remove-ariaLabel.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(Alert): removed aria-label prop

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-appendTo-default.js, packages/eslint-plugin-pf-codemods/test/rules/v5/popover-appendTo-default.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(Popover): Updated appendTo default value

packages/eslint-plugin-pf-codemods/lib/rules/v5/masthead-update-component.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/pageheader-update-logoComponent.js, packages/eslint-plugin-pf-codemods/test/rules/v5/masthead-update-component.js, packages/eslint-plugin-pf-codemods/test/rules/v5/pageheader-update-logoComponent.js, packages/pf-codemods/README.md
=> chore(Masthead, PageHeader): component type default changed

packages/eslint-plugin-pf-codemods/lib/rules/v5/dropdownItem-remove-isHovered.js, packages/eslint-plugin-pf-codemods/test/rules/v5/dropdownItem-remove-isHovered.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(DropdownItem): remove ishovered prop

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/table-warn-thExpandType.js, packages/eslint-plugin-pf-codemods/test/rules/v5/table-warn-thExpandType.js, packages/pf-codemods/README.md
=> chore(Table): collapseAllAriaLabel type update warning

packages/eslint-plugin-pf-codemods/lib/rules/v5/notificationBadge-remove-isRead.js, packages/eslint-plugin-pf-codemods/test/rules/v5/notificationBadge-remove-isRead.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(NotificationBadge): remove isRead prop

packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-lightThemeObjects.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-remove-ChartThemeVariant.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-remove-darkThemeObjects.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-remove-themeVariant.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-lightThemeObjects.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-remove-ChartThemeVariant.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-remove-darkThemeObjects.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-remove-themeVariant.js, packages/pf-codemods/README.md, test/test.tsx
=> fix(Charts): removed theme variant

packages/eslint-plugin-pf-codemods/index.js
=> fix(index): dynamically resolve path to rules

packages/eslint-plugin-pf-codemods/lib/rules/v5/applicationLauncher-warn-input.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/card-warn-component.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-lightThemeObjects.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-remove-darkThemeObjects.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-resizeObserver-import.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-tooltip-warning.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/key-codes-removed.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/react-dropzone-warn-upgrade.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/table-warn-actionsColumn.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/tabs-warn-children-type-changed.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/wizard-warn-button-order.js, packages/eslint-plugin-pf-codemods/test/rules/v5/card-warn-component.js, test/test.tsx
=> fix(various): some rules failing on certain import syntax

packages/eslint-plugin-pf-codemods/lib/rules/v5/toolbarVarious-remove-alignment.js, packages/eslint-plugin-pf-codemods/test/rules/v5/toolbarVarious-remove-alignment.js, packages/pf-codemods/README.md
=> feat(Toolbar): remove/replace alignment prop for a few components

packages/eslint-plugin-pf-codemods/lib/rules/v5/react-dropzone-warn-upgrade.js, packages/eslint-plugin-pf-codemods/test/rules/v5/react-dropzone-warn-upgrade.js
Based on feedback from the alpha testing
=> chore(react-dropzone): Updated warning message

packages/eslint-plugin-pf-codemods/lib/rules/v5/numberInput-remove-allowEmptyInput.js, packages/eslint-plugin-pf-codemods/test/rules/v5/numberInput-remove-allowEmptyInput.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(NumberInput): remove allowEmptyInput prop

packages/eslint-plugin-pf-codemods/index.js, test/test.tsx
=> chore(config): disable noInlineConfig

packages/eslint-plugin-pf-codemods/index.js, test/test.tsx
Reverts patternfly/pf-codemods#298
=> Revert "chore(config): disable noInlineConfig"

packages/pf-codemods/index.js, test/test.tsx
Another attempt at addressing #297
=> chore(warnings): suppress eslint-disable-next-line messages

packages/eslint-plugin-pf-codemods/lib/rules/v5/pagination-rename-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/pagination-rename-props.js, packages/pf-codemods/README.md, test/test.tsx
=> fix(Pagination): updated codemod for prop renaming

packages/eslint-plugin-pf-codemods/lib/rules/v5/popper-remove-popperMatchesTriggerWidth.js, packages/eslint-plugin-pf-codemods/test/rules/v5/popper-remove-popperMatchesTriggerWidth.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(Popper):remove popperMatchesTriggerWidth prop

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/label-remove-isTruncated.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/label-warn-truncated-default.js, packages/eslint-plugin-pf-codemods/test/rules/v5/label-remove-isTruncated.js, packages/eslint-plugin-pf-codemods/test/rules/v5/label-warn-truncated-default.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Label): remove isTruncated from Label

packages/eslint-plugin-pf-codemods/lib/rules/v5/checkbox-reorder-onChange-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/checkbox-reorder-onChange-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Checkbox): reorder onChange params

packages/eslint-plugin-pf-codemods/lib/rules/v5/calendarMonth-update-onChange-onMonthChange-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/calendarMonth-update-onChange-onMonthChange-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(CalendarMonth): update onChange and onMonthChange params

packages/eslint-plugin-pf-codemods/lib/rules/v5/menu-moved-ariaLabel.js, packages/eslint-plugin-pf-codemods/test/rules/v5/menu-moved-ariaLabel.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(Menu): moved arialabel from Menu to MenuList

packages/eslint-plugin-pf-codemods/test/rules/v5/dropdown-update-deprecatedPath.js, packages/eslint-plugin-pf-codemods/test/rules/v5/optionsMenu-deprecated.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js
=> chore - updated moveSpecifier test helper

packages/eslint-plugin-pf-codemods/lib/rules/v5/contextSelector-update-deprecatedPath.js, packages/eslint-plugin-pf-codemods/test/rules/v5/contextSelector-update-deprecatedPath.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(ContextSelector): update imports to deprecated

packages/eslint-plugin-pf-codemods/lib/rules/v5/datalist-remove-selectableRow.js, packages/eslint-plugin-pf-codemods/test/rules/v5/datalist-remove-selectableRow.js, packages/pf-codemods/README.md, test/test.tsx
Closes: https://github.com/patternfly/pf-codemods/issues/268
=> feat(DataList): update selectableRow.onChange to onSelectableRowChange

packages/eslint-plugin-pf-codemods/lib/helpers.js
=> fix error thrown when space missing before callback arg

packages/eslint-plugin-pf-codemods/lib/rules/v5/tableComposable-remove-hasSelectableRowCaption.js, packages/eslint-plugin-pf-codemods/test/rules/v5/tableComposable-remove-hasSelectableRowCaption.js
=> fix(TableComposable): rule was looking in wrong import src

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js
=> fix(addCallBackParam): helper will now also check deprecated import src

packages/pf-codemods/index.js
https://eslint.org/docs/latest/use/migrate-to-8.0.0
=> Replace usage of the CLIEngine and other deprecated APIs in eslint 8

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/emptyState-warn-change-structure.js, packages/eslint-plugin-pf-codemods/test/rules/v5/emptyState-warn-change-structure.js, packages/pf-codemods/README.md
Closes: https://github.com/patternfly/pf-codemods/issues/376
=> fix(EmptyState): codemod issues

generators/write-rule.js, packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/aboutModalBoxHero-remove-subcomponent.js, packages/eslint-plugin-pf-codemods/test/rules/v5/aboutModalBoxHero-remove-subcomponent.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(AboutModal): removed AboutModalBoxHero

packages/eslint-plugin-pf-codemods/lib/rules/v5/backgroundImage-update-props.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/backgroundImageSrcMap-remove-interface.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/loginPage-update-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/backgroundImage-update-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/backgroundImageSrcMap-remove-interface.js, packages/eslint-plugin-pf-codemods/test/rules/v5/loginPage-update-props.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(BackgroundImage/LoginPage): updated props

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/radio-update-onChange-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/radio-update-onChange-params.js, packages/pf-codemods/README.md, test/test.tsx
=> fix(Radio): updated onChange param order

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/slider-update-onChangeParams.js, packages/eslint-plugin-pf-codemods/test/rules/v5/slider-update-onChangeParams.js, packages/pf-codemods/README.md, test/test.tsx
=> fix(Slider): added event param to onChange

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js
=> feat(helpers): Stop reporting errors after a param add/swap is fixed

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/dropdownToggleCheckbox-update-onChange.js, packages/eslint-plugin-pf-codemods/test/rules/v5/dropdownToggleCheckbox-update-onChange.js, packages/pf-codemods/README.md, test/test.tsx
closes #356
discovered a bug: #359
=> feat(DropdownToggleCheckbox): change param order for onChange

packages/eslint-plugin-pf-codemods/lib/rules/v5/fileUpload-event-params-added-to-callbacks.js, packages/eslint-plugin-pf-codemods/test/rules/v5/fileUpload-event-params-added-to-callbacks.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(FileUpload): Added events params to callbacks

packages/eslint-plugin-pf-codemods/lib/rules/v5/table-update-deprecatedPath.js, packages/eslint-plugin-pf-codemods/test/rules/v5/table-update-deprecatedPath.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Table): update paths to reference deprecated directory

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-swap-shouldClose-shouldOpen-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/popover-swap-shouldClose-shouldOpen-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Popover): Swap param order for shouldClose and shouldOpen

packages/eslint-plugin-pf-codemods/lib/rules/v5/page-rename-props.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/pageSidebar-update-api.js, packages/eslint-plugin-pf-codemods/test/rules/v5/page-rename-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/pageSidebar-update-api.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Page): updated API and renamed props

packages/eslint-plugin-pf-codemods/lib/rules/v5/various-rename-default.js, packages/eslint-plugin-pf-codemods/test/rules/v5/various-rename-default.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(various): rename 'default' option to 'custom'

packages/eslint-plugin-pf-codemods/lib/rules/v5/toggleGroupItem-swap-onChange-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/toggleGroupItem-swap-onChange-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(ToggleGroupItem): Swap onChange params

packages/eslint-plugin-pf-codemods/lib/rules/v5/page-updated-callback.js, packages/eslint-plugin-pf-codemods/test/rules/v5/page-updated-callback.js, packages/pf-codemods/README.md, test/test.tsx
=> chore(page): add event to onPageResize

packages/eslint-plugin-pf-codemods/lib/rules/v5/textInput-swap-onChange-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/textInput-swap-onChange-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(TextInput): Swap onChange params

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/table-rename-TableComposable.js, packages/eslint-plugin-pf-codemods/test/rules/v5/table-rename-TableComposable.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Table): rename TableComposable to Table

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/pageHeader-deprecated.js, packages/eslint-plugin-pf-codemods/test/rules/v5/pageHeader-deprecated.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(PageHeader): deprecate PageHeader - update imports

packages/eslint-plugin-pf-codemods/test/rules/v5/charts-lightThemeObjects.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-remove-ChartThemeVariant.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-remove-themeVariant.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-resizeObserver-import.js
=> chore(Charts): added additional dist tests

packages/eslint-plugin-pf-codemods/lib/rules/v5/inputGroup-add-inputGroupItem.js, packages/eslint-plugin-pf-codemods/test/rules/v5/inputGroup-add-inputGroupItem.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(InputGroup): added InputGroupItem

packages/eslint-plugin-pf-codemods/index.js
=> chore(ExpandableSection): Remove from beta list

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-swap-shouldClose-shouldOpen-params.js, packages/pf-codemods/README.md
=> chore(Popover): Remove param swapping rule from beta

packages/eslint-plugin-pf-codemods/lib/rules/v5/loginForm-update-callback-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/loginForm-update-callback-params.js, packages/pf-codemods/README.md, test/test.tsx
=> fix(LoginForm): updated callback param order

packages/eslint-plugin-pf-codemods/lib/rules/v5/textArea-swap-onChange-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/textArea-swap-onChange-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(TextArea): Swap onChange params

packages/eslint-plugin-pf-codemods/lib/rules/v5/editableSelectInputCell-onSelect-clearSelection-swap-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/editableSelectInputCell-onSelect-clearSelection-swap-params.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(EditableSelectInputCell): Add params for onSelect, clearSelection

packages/eslint-plugin-pf-codemods/lib/rules/v5/tabs-onToggle-add-event-param.js, packages/eslint-plugin-pf-codemods/test/rules/v5/tabs-onToggle-add-event-param.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Tabs): Add event param to onToggle

packages/eslint-plugin-pf-codemods/lib/rules/v5/inputGroupText-remove-variant.js, packages/eslint-plugin-pf-codemods/test/rules/v5/inputGroupText-remove-variant.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(inputGroupText): Remove variant prop

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js, test/test.tsx
=> fix(moveSpecifiers helper): updated logic for nested elements

packages/eslint-plugin-pf-codemods/lib/rules/v5/selectDropdown-rename-itemId.js, packages/eslint-plugin-pf-codemods/test/rules/v5/selectDropdown-rename-itemId.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Select,Dropdown): renamed itemId prop

packages/eslint-plugin-pf-codemods/index.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/deprecatedSelect-warn-markupUpdated.js, packages/eslint-plugin-pf-codemods/test/rules/v5/deprecatedSelect-warn-markupUpdated.js, packages/pf-codemods/README.md, test/test.tsx
=> fix(select deprecated): updated markup

packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-remove-props.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/popover-swap-shouldClose-shouldOpen-params.js, packages/eslint-plugin-pf-codemods/test/rules/v5/popover-remove-props.js, packages/eslint-plugin-pf-codemods/test/rules/v5/popover-swap-shouldClose-shouldOpen-params.js
=> fix: popover shouldclose - event and tip changes

packages/eslint-plugin-pf-codemods/index.js
=> chore(deprecated): added codemods to setup array

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/nextComponents-update-path.js, packages/eslint-plugin-pf-codemods/lib/rules/v5/no-unused-imports-v5.js, packages/eslint-plugin-pf-codemods/test/rules/v5/nextComponents-update-path.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js, packages/pf-codemods/README.md, test/test.tsx
=> feat(Next components): updated import and export paths

packages/pf-codemods/README.md
=> chore(readme): add manual change example for helpertext

packages/pf-codemods/README.md
=> docs(README): correct import in nextComponents-update-path rule

packages/eslint-plugin-pf-codemods/lib/rules/v5/charts-various-imports.js, packages/eslint-plugin-pf-codemods/test/rules/v5/charts-various-imports.js, packages/pf-codemods/README.md
=> fix(Charts): raised error for cleaned up exports

packages/eslint-plugin-pf-codemods/lib/helpers.js, packages/eslint-plugin-pf-codemods/test/testHelpers.js
=> fix(move specifiers) keep inputkind while moving specifiers

packages/pf-codemods/README.md
Went through to update other formatting/link issues, removed duplicate rules, etc. Tried to check that each rule's link was also correct (linking to the correct PR and not an issue). Wanted to get at least 1 review to make sure I didn't miss anything so that we don't need another fix
=> chore(README): fixed formatting and links

packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js, packages/eslint-plugin-pf-codemods/test/rules/v5/cardHeader-update-api.js
Closes #524 
@gitdallas this runs into the possible issue that the test file has a "first run" and "second run" test due to the way the fix works. Testing in the `test.tsx` file things look to work as intended, though.
=> fix(CardHeader): updated logic to take into account conditional rendering

.gitignore, packages/class-name-updater/classNameUpdate.js, test/test.tsx
=> feat(class-name-updater): Add support for theme and global classes

packages/class-name-updater/classNameUpdate.js
Adds pf-color- to pf-v5-color update support to the class name updater.
=> feat(class-name-updater): Add support for color class names

packages/eslint-plugin-pf-codemods/src/rules/v6/buttonRenameIsActive/button-rename-isActive.md, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonRenameIsActive/button-rename-isActive.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonRenameIsActive/button-rename-isActive.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonRenameIsActive/buttonRenameIsActiveInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonRenameIsActive/buttonRenameIsActiveOutput.tsx
=> feat(Button): Rename isActive to isClicked

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/simpleFileUploadWarnChanges/simpleFileUpload-warn-changes.md, packages/eslint-plugin-pf-codemods/src/rules/v6/simpleFileUploadWarnChanges/simpleFileUpload-warn-changes.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/simpleFileUploadWarnChanges/simpleFileUpload-warn-changes.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/simpleFileUploadWarnChanges/simpleFileUploadWarnChangesInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/simpleFileUploadWarnChanges/simpleFileUploadWarnChangesOutput.tsx
=> feat(SimpleFileUpload): added rule to warn about component changes

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/notificationBadgeWarnMarkupChange/notificationBadge-warn-markup-change.md, packages/eslint-plugin-pf-codemods/src/rules/v6/notificationBadgeWarnMarkupChange/notificationBadge-warn-markup-change.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/notificationBadgeWarnMarkupChange/notificationBadge-warn-markup-change.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/notificationBadgeWarnMarkupChange/notificationBadgeWarnMarkupChangeInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/notificationBadgeWarnMarkupChange/notificationBadgeWarnMarkupChangeOutput.tsx
=> feat(NotificationBadge) warn about markup updated

packages/eslint-plugin-pf-codemods/src/rules/v6/cardRemoveVariousProps/card-remove-various-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/cardRemoveVariousProps/card-remove-various-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/cardRemoveVariousProps/card-remove-various-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/cardRemoveVariousProps/cardRemoveVariousPropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/cardRemoveVariousProps/cardRemoveVariousPropsOutput.tsx
=> feat(Card): Remove deprecated and unused props

packages/eslint-plugin-pf-codemods/src/rules/v6/accordionItemWarnUpdateMarkup/accordionItem-warn-update-markup.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggle-move-isExpanded-prop.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/drawerHeadWarnUpdatedMarkup/drawerHead-warn-updated-markup.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/drawerReplaceColorVariantLight200/drawer-replace-colorVariant-light200.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/helperTextItemWarnScreenReaderTextUpdate/helperTextItem-warn-screenReaderText-update.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/simpleFileUploadWarnChanges/simpleFileUpload-warn-changes.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/tabsReplaceVariantLight300/tabs-replace-variant-light300.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/tabsUpdateMarkup/tabs-update-markup.ts
=> chore(rules): type existing rules

packages/eslint-plugin-pf-codemods/src/rules/v6/avatarReplaceBorderForIsBordered/avatar-replace-border-for-isBordered.md, packages/eslint-plugin-pf-codemods/src/rules/v6/avatarReplaceBorderForIsBordered/avatar-replace-border-for-isBordered.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/avatarReplaceBorderForIsBordered/avatar-replace-border-for-isBordered.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/avatarReplaceBorderForIsBordered/avatarReplaceBorderForIsBorderedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/avatarReplaceBorderForIsBordered/avatarReplaceBorderForIsBorderedOutput.tsx, yarn.lock
=> feat(Avatar) replace border with isBordered

packages/eslint-plugin-pf-codemods/src/rules/helpers/getFromPackage.ts
=> fix(getFromPackage): add parameter to filter imports and exports by names

packages/eslint-plugin-pf-codemods/src/rules/helpers/findAncestor.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/helpers.js, packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/accordionToggleMoveIsExpandedProp/accordionToggle-move-isExpanded-prop.ts
=> chore(helpers): extract findAncestor helper

packages/eslint-plugin-pf-codemods/src/rules/v6/loginMainFooterLinksItemStructureUpdated/loginMainFooterLinksItem-structure-updated.md, packages/eslint-plugin-pf-codemods/src/rules/v6/loginMainFooterLinksItemStructureUpdated/loginMainFooterLinksItem-structure-updated.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/loginMainFooterLinksItemStructureUpdated/loginMainFooterLinksItem-structure-updated.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/loginMainFooterLinksItemStructureUpdated/loginMainFooterLinksItemStructureUpdatedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/loginMainFooterLinksItemStructureUpdated/loginMainFooterLinksItemStructureUpdatedOutput.tsx
=> feat(LoginMainFooterLinksItem): pass children instead of props

packages/eslint-plugin-pf-codemods/src/rules/v6/dragDropDeprecated/dragDrop-deprecated.md, packages/eslint-plugin-pf-codemods/src/rules/v6/dragDropDeprecated/dragDrop-deprecated.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/dragDropDeprecated/dragDrop-deprecated.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/dragDropDeprecated/dragDropDeprecatedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/dragDropDeprecated/dragDropDeprecatedOutput.tsx
=> feat(DragDrop): deprecate

packages/eslint-plugin-pf-codemods/src/rules/helpers/JSXAttributes.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/helpers.js, packages/eslint-plugin-pf-codemods/src/rules/helpers/pfPackageMatches.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarUpdateAlignValues/toolbar-update-align-values.md, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarUpdateAlignValues/toolbar-update-align-values.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarUpdateAlignValues/toolbar-update-align-values.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarUpdateAlignValues/toolbarUpdateAlignValuesInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarUpdateAlignValues/toolbarUpdateAlignValuesOutput.tsx
=> fix(Toolbar): updated align values to logical names

packages/eslint-plugin-pf-codemods/src/rules/v6/bannerReplaceVariantProp/banner-replace-variantProp.md, packages/eslint-plugin-pf-codemods/src/rules/v6/bannerReplaceVariantProp/banner-replace-variantProp.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/bannerReplaceVariantProp/banner-replace-variantProp.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/bannerReplaceVariantProp/bannerReplaceVariantPropInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/bannerReplaceVariantProp/bannerReplaceVariantPropOutput.tsx
=> feat(Banner): added color and status props

packages/eslint-plugin-pf-codemods/src/rules/v6/pageRenameHeader/page-rename-header.md, packages/eslint-plugin-pf-codemods/src/rules/v6/pageRenameHeader/page-rename-header.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/pageRenameHeader/page-rename-header.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/pageRenameHeader/pageRenameHeaderInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/pageRenameHeader/pageRenameHeaderOutput.tsx
=> feat(Page): rename header to masthead

packages/pf-codemods/package.json
This reverts commit fe3aef530ede2a8821bb71b088bbd63fa4118bab.
=> Revert "fix: packages/pf-codemods/package.json to reduce vulnerabilities (#650)"

packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyState-nonExported-components.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateNonExportedComponents/emptyState-nonExported-components.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarItemWarnUpdateMarkup/toolbarItem-warn-update-markup.ts
=> fix(EmptyState): resolved rule being flagged for every specifier

packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorDeprecated/dualListSelector-deprecated.md, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorDeprecated/dualListSelector-deprecated.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorDeprecated/dualListSelector-deprecated.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorDeprecated/dualListSelectorDeprecatedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorDeprecated/dualListSelectorDeprecatedOutput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorNextPromoted/dualListSelectorNext-promoted.md, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorNextPromoted/dualListSelectorNext-promoted.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorNextPromoted/dualListSelectorNext-promoted.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorNextPromoted/dualListSelectorNextPromotedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/dualListSelectorNextPromoted/dualListSelectorNextPromotedOutput.tsx
Closes #637
This or #660 will need a rebase once either goes in
=> feat(DualListSelector): promoted Next implementation

packages/eslint-plugin-pf-codemods/src/rules/v6/switchRemoveLabelOff/switch-remove-labelOff.md, packages/eslint-plugin-pf-codemods/src/rules/v6/switchRemoveLabelOff/switch-remove-labelOff.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/switchRemoveLabelOff/switch-remove-labelOff.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/switchRemoveLabelOff/switchRemoveLabelOffInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/switchRemoveLabelOff/switchRemoveLabelOffOutput.tsx
=> fix(Switch): removed labelOff prop for a11y

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/popperUpdateAppendToDefault/popper-update-appendTo-default.md, packages/eslint-plugin-pf-codemods/src/rules/v6/popperUpdateAppendToDefault/popper-update-appendTo-default.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/popperUpdateAppendToDefault/popper-update-appendTo-default.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/popperUpdateAppendToDefault/popperUpdateAppendToDefaultInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/popperUpdateAppendToDefault/popperUpdateAppendToDefaultOutput.tsx
=> fix(Popper): updated default of appendTo prop

packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/button-moveIcons-icon-prop.md, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/button-moveIcons-icon-prop.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/button-moveIcons-icon-prop.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/buttonMoveIconsIconPropInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/buttonMoveIconsIconProp/buttonMoveIconsIconPropOutput.tsx
=> feat(Button): updated icon usage

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/logViewerMovedStyles/logViewer-moved-styles.md, packages/eslint-plugin-pf-codemods/src/rules/v6/logViewerMovedStyles/logViewer-moved-styles.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/logViewerMovedStyles/logViewer-moved-styles.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/logViewerMovedStyles/logViewerMovedStylesInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/logViewerMovedStyles/logViewerMovedStylesOutput.tsx
Closes #676 
Just provides a warning for now, figure we can followup with an actual fix if necessary/time permits.
=> fix(LogViewer): moved styles into repo

packages/eslint-plugin-pf-codemods/src/rules/v6/removeDeprecatedComponents/remove-deprecated-components.md, packages/eslint-plugin-pf-codemods/src/rules/v6/removeDeprecatedComponents/remove-deprecated-components.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/removeDeprecatedComponents/remove-deprecated-components.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/removeDeprecatedComponents/removeDeprecatedComponentsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/removeDeprecatedComponents/removeDeprecatedComponentsOutput.tsx
Closes #664 
Note that we can remove KebabToggle from this rule once we get something for #683 up
=> feat(various): removed deprecated components

packages/eslint-plugin-pf-codemods/src/rules/v6/colorPropsReplacedColors/colorProps-replaced-colors.md, packages/eslint-plugin-pf-codemods/src/rules/v6/colorPropsReplacedColors/colorProps-replaced-colors.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/colorPropsReplacedColors/colorProps-replaced-colors.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/colorPropsReplacedColors/colorPropsReplacedColorsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/colorPropsReplacedColors/colorPropsReplacedColorsOutput.tsx
=> feat(Banner,Label): renamed cyan/gold color values

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarGroupUpdatedIconButtonGroupVariant/toolbarGroup-updated-iconButtonGroup-variant.md, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarGroupUpdatedIconButtonGroupVariant/toolbarGroup-updated-iconButtonGroup-variant.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarGroupUpdatedIconButtonGroupVariant/toolbarGroup-updated-iconButtonGroup-variant.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarGroupUpdatedIconButtonGroupVariant/toolbarGroupUpdatedIconButtonGroupVariantInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarGroupUpdatedIconButtonGroupVariant/toolbarGroupUpdatedIconButtonGroupVariantOutput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarLabelGroupContentUpdatedMarkup/toolbarLabelGroupContent-updated-markup.md, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarLabelGroupContentUpdatedMarkup/toolbarLabelGroupContent-updated-markup.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarLabelGroupContentUpdatedMarkup/toolbarLabelGroupContent-updated-markup.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarLabelGroupContentUpdatedMarkup/toolbarLabelGroupContentUpdatedMarkupInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarLabelGroupContentUpdatedMarkup/toolbarLabelGroupContentUpdatedMarkupOutput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbar-remove-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbar-remove-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbar-remove-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbarRemovePropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbarRemovePropsOutput.tsx
=> fix(Toolbar): updated for parity with Core updates

packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/removeElement.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/removeEmptyLineAfter.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.ts
=> chore(EmptyState): Tailor message content to be more relevant

packages/eslint-plugin-pf-codemods/src/rules/v6/navItemRemoveHasNavLinkWrapperProp/navItem-remove-hasNavLinkWrapper-prop.md, packages/eslint-plugin-pf-codemods/src/rules/v6/navItemRemoveHasNavLinkWrapperProp/navItem-remove-hasNavLinkWrapper-prop.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/navItemRemoveHasNavLinkWrapperProp/navItem-remove-hasNavLinkWrapper-prop.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/navItemRemoveHasNavLinkWrapperProp/navItemRemoveHasNavLinkWrapperPropInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/navItemRemoveHasNavLinkWrapperProp/navItemRemoveHasNavLinkWrapperPropOutput.tsx
=> feat(NavItem): added default nav item wrapper

packages/eslint-plugin-pf-codemods/src/ruleCustomization.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/paginationWarnMarkupChanged/pagination-warn-markup-changed.md, packages/eslint-plugin-pf-codemods/src/rules/v6/paginationWarnMarkupChanged/pagination-warn-markup-changed.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/paginationWarnMarkupChanged/pagination-warn-markup-changed.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/paginationWarnMarkupChanged/paginationWarnMarkupChangedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/paginationWarnMarkupChanged/paginationWarnMarkupChangedOutput.tsx
=> feat(Pagination): added wrapper around menu toggle

packages/eslint-plugin-pf-codemods/src/rules/helpers/getRemoveElementFixes.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/index.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeader-move-into-emptyState.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeaderMoveIntoEmptyStateInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/emptyStateHeaderMoveIntoEmptyState/emptyStateHeaderMoveIntoEmptyStateOutput.tsx
=> feat(EmptyState): Add auto fix support for some child components

packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/textReplaceWithContentOutput.tsx
=> fix(Text): Replace TextVariants and TextProps with Content

packages/eslint-plugin-pf-codemods/src/rules/helpers/getFromPackage.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/interfaces.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/renameProps.ts, packages/eslint-plugin-pf-codemods/src/rules/helpers/renamePropsOnNode.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/component-groups-multi-content-card-remove-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/component-groups-multi-content-card-remove-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/component-groups-multi-content-card-remove-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/componentGroupsMultiContentCardRemovePropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/componentGroupsMultiContentCardRemovePropsOutput.tsx
=> feat(MultiContentCard): Remove leftBorderVariant and withHeaderBorder

packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsErrorStateRenameProps/componentGroups-errorState-rename-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsErrorStateRenameProps/componentGroups-errorState-rename-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsErrorStateRenameProps/componentGroups-errorState-rename-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsErrorStateRenameProps/componentGroupsErrorStateRenamePropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsErrorStateRenameProps/componentGroupsErrorStateRenamePropsOutput.tsx
=> feat(ErrorState): rename props

packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/component-groups-multi-content-card-remove-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/component-groups-unavailable-content-rename-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/component-groups-unavailable-content-rename-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/component-groups-unavailable-content-rename-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/componentGroupsUnavailableContentRenamePropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsUnavailableContentRenameProps/componentGroupsUnavailableContentRenamePropsOutput.tsx
Closes #671
Also fixes an incorrect link in my MultiContentCard codemod readme.
=> feat(UnavailableContent): Rename props

packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/component-groups-invalidObject-rename-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/component-groups-invalidObject-rename-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/component-groups-invalidObject-rename-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/componentGroupsInvalidObjectRenamePropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsInvalidObjectRenameProps/componentGroupsInvalidObjectRenamePropsOutput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/componentGroupsMultiContentCardRemoveProps/component-groups-multi-content-card-remove-props.md
=> feat(InvalidObject): rename props

packages/class-name-updater/src/classNameUpdate.ts
=> fix(class-name-updater): ignore css vars when running in v6 mode

packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbar-remove-props.md, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbar-remove-props.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbar-remove-props.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbarRemovePropsInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/toolbarRemoveProps/toolbarRemovePropsOutput.tsx
Towards https://github.com/patternfly/pf-codemods/issues/749
=> feat(ToolbarItem): remove widths prop

packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSection-update-variant-values.ts
Fixes an error @mfrances17 is encountering when attempting a product migration
=> Fix(pageSection): Fix error attempting to access attribute of undefined

packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modal-deprecated.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modal-deprecated.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modalDeprecatedInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/modalDeprecated/modalDeprecatedOutput.tsx
=> chore(Modal): added ModalProps to moveSpecifier arrays

packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.test.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chip-replace-with-label.ts, packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chipReplaceWithLabelInput.tsx, packages/eslint-plugin-pf-codemods/src/rules/v6/chipReplaceWithLabel/chipReplaceWithLabelOutput.tsx
=> fix(chipGroup): Replace numChips with numLabels
